from typing import Protocol, List, Optional
from app.chat.domain.chat_message_entity import ChatMessage
from app.chat.domain.dtos import InboxSummary, ChatUser


class IChatRepository(Protocol):
    def get_conversation(self, user1_id: int, user2_id: int) -> List[ChatMessage]: ...
    def save_message(self, sender_id: int, receiver_id: int, content: str) -> ChatMessage: ...
    def get_inbox(self, current_user_id: int) -> List[InboxSummary]: ...


class IChatUserLookup(Protocol):
    def get_users_by_ids(self, user_ids: List[int]) -> List[ChatUser]: ...


class IChatContactsLookup(Protocol):
    def get_doctor_id_for_doctor(self, user_id: int) -> Optional[int]: ...
    def get_doctor_id_for_receptionist(self, user_id: int) -> Optional[int]: ...
    def get_doctor_id_for_patient(self, user_id: int) -> Optional[int]: ...
    def get_patients_of_doctor(self, doctor_id: int) -> List[ChatUser]: ...
    def get_receptionists_of_doctor(self, doctor_id: int) -> List[ChatUser]: ...
    def get_doctor_contact(self, doctor_id: int) -> Optional[ChatUser]: ...
