"""Puerto de lectura de credenciales/perfil para el login.

El use case depende solo de esta abstracción; la implementación concreta
(`AuthReadRepository`) lee la DB compartida vía los read-models de auth.
"""
from typing import Optional, List, Protocol, Tuple
from datetime import datetime


class IAuthReadPort(Protocol):
    def get_user_by_email(self, email: str): ...
    def get_user_by_id(self, user_id: int): ...
    def get_patient_by_user_id(self, user_id: int): ...
    def get_doctor_by_user_id(self, user_id: int): ...
    def get_receptionist_by_user_id(self, user_id: int): ...
    def get_receptionists_by_doctor_id(self, doctor_id: int) -> List: ...
    def get_medical_record_id(self, patient_id: int, doctor_id: int) -> Optional[int]: ...
    def get_subscription_status(self, user_id: int) -> Optional[Tuple[str, Optional[datetime]]]: ...
