from typing import List, Optional, Protocol
from app.features.forums.domain.entities import (
    SocialProfileEntity,
    CommunityGroupEntity,
    PostEntity,
    CommentEntity,
    ReportEntity
)

class IForumsRepository(Protocol):
    def create_profile(self, profile: SocialProfileEntity) -> SocialProfileEntity:...
    def get_profile(self, user_id: int) -> Optional[SocialProfileEntity]:...
    def create_group(self, group: CommunityGroupEntity) -> CommunityGroupEntity:...
    def get_groups(self) -> List[CommunityGroupEntity]:...
    def create_post(self, post: PostEntity) -> PostEntity:...  
    def get_global_feed(self, limit: int = 50, offset: int = 0) -> List[PostEntity]:...
    def get_group_feed(self, group_id: int, limit: int = 50, offset: int = 0) -> List[PostEntity]:...
    def add_comment(self, comment: CommentEntity) -> CommentEntity:...
    def get_comments(self, post_id: int) -> List[CommentEntity]:...
    def create_report(self, report: ReportEntity) -> ReportEntity:...
