from typing import List, Optional, Protocol
from app.features.forums.domain.social_profile_entity import SocialProfileEntity
from app.features.forums.domain.community_group_entity import CommunityGroupEntity
from app.features.forums.domain.post_entity import PostEntity
from app.features.forums.domain.comment_entity import CommentEntity
from app.features.forums.domain.report_entity import ReportEntity

class IForumsRepository(Protocol):
    def create_profile(self, profile: SocialProfileEntity) -> SocialProfileEntity:...
    def get_profile(self, user_id: int) -> Optional[SocialProfileEntity]:...
    def update_cluster_profile(self, user_id: int, cluster: str) -> None:...
    def create_group(self, group: CommunityGroupEntity) -> CommunityGroupEntity:...
    def get_groups(self) -> List[CommunityGroupEntity]:...
    def get_groups_by_cluster(self, cluster: str) -> List[CommunityGroupEntity]:...
    def create_post(self, post: PostEntity) -> PostEntity:...
    def get_global_feed(self, limit: int = 50, offset: int = 0) -> List[PostEntity]:...
    def get_feed_by_cluster(self, cluster: str, limit: int = 50, offset: int = 0) -> List[PostEntity]:...
    def get_ads(self, limit: int = 20) -> List[PostEntity]:...
    def count_ads_by_author_since(self, author_id: int, since) -> int:...
    def get_group_feed(self, group_id: int, limit: int = 50, offset: int = 0) -> List[PostEntity]:...
    def add_comment(self, comment: CommentEntity) -> CommentEntity:...
    def get_comments(self, post_id: int) -> List[CommentEntity]:...
    def create_report(self, report: ReportEntity) -> ReportEntity:...

class IPatientClusterLookup(Protocol):
    def get_cluster_by_user_id(self, user_id: int) -> Optional[str]:...

class IAdEligibilityLookup(Protocol):
    def is_premium_active(self, user_id: int) -> bool:...
