from typing import Protocol, List, Optional
from app.notifications.domain.notification_entity import NotificationEntity


class INotificationRepository(Protocol):
    def create(self, notification: NotificationEntity) -> NotificationEntity: ...
    def get_by_user_id(self, user_id: int, limit: int = 50) -> List[NotificationEntity]: ...
    def mark_as_read(self, notification_id: int, user_id: int) -> bool: ...
