from typing import Protocol, Optional, List
from .medical_record_entity import MedicalRecordEntity
from .risk_prediction_entity import RiskPredictionEntity
from .dtos import PatientInfo

class IMedicalRecordRepository(Protocol):
    def get_by_patient_and_doctor(self, patient_id: int, doctor_id: int) -> Optional[MedicalRecordEntity]:...
    def get_by_id(self, medical_record_id: int) -> Optional[MedicalRecordEntity]:...
    def create(self, data: MedicalRecordEntity) -> MedicalRecordEntity:...
    def update(self, medical_record_id: int, data: dict) -> Optional[MedicalRecordEntity]:...
    
class IPatientInfoPort(Protocol):
    def get_patient_info(self, patient_id: int) -> Optional[PatientInfo]:...
    def get_patients_by_doctor(self, doctor_id: int) -> List[PatientInfo]:...

class IMLPredictionService(Protocol):
    def predict(self, patient: PatientInfo, medical_record: MedicalRecordEntity, latest_diary: Optional[object]) -> Optional[dict]:...

class IRiskPredictionRepository(Protocol):
    def create(self, data: RiskPredictionEntity) -> RiskPredictionEntity:...
    def get_latest_for_medical_record(self, medical_record_id: int) -> Optional[RiskPredictionEntity]:...
