from typing import Protocol, List, Optional
from app.features.appointments.domain.entities import AppointmentEntity

class IAppointmentRepository(Protocol):
    def get_by_id(self, appointment_id: int) -> Optional[AppointmentEntity]: ...
    def get_by_patient_id(self, patient_id: int) -> List[AppointmentEntity]: ...
    def get_by_doctor_id(self, doctor_id: int) -> List[AppointmentEntity]: ...
    def create(self, appointment_entity: AppointmentEntity) -> AppointmentEntity: ...
    def update(self, appointment_entity: AppointmentEntity) -> AppointmentEntity: ...
    def delete(self, appointment_id: int) -> None: ...
