from typing import List, Optional, Dict
from typing import Protocol, Optional, List
from app.users.domain.user_entity import UserEntity
from app.users.domain.doctor_entity import DoctorEntity
from app.users.domain.patient_entity import PatientEntity
from app.users.domain.receptionist_entity import ReceptionistEntity
from app.users.domain.invitation_code_entity import InvitationCodeEntity
from app.users.domain.unlink_request_entity import UnlinkRequestEntity
from salud_prenatal_shared_core.enums import RoleEnum

class IUserRepository(Protocol):
    def get_by_email(self, email: str) -> Optional[UserEntity]: ...
    def get_by_id(self, user_id: int) -> Optional[UserEntity]: ...
    def get_by_ids(self, user_ids: List[int]) -> List[UserEntity]: ...
    def get_by_role(self, role: RoleEnum) -> List[UserEntity]: ...
    def get_all(self, skip: int = 0, limit: int = 100) -> List[UserEntity]: ...
    def create(self, user: UserEntity) -> UserEntity: ...
    def update(self, user_id: int, user_data: UserEntity) -> Optional[UserEntity]: ...
    def delete(self, user_id: int) -> Optional[UserEntity]: ...

class IDoctorRepository(Protocol):
    def get_by_user_id(self, user_id: int) -> Optional[DoctorEntity]: ...
    def create(self, doctor: DoctorEntity) -> DoctorEntity: ...
    def update(self, doctor_id: int, doctor_data: DoctorEntity) -> Optional[DoctorEntity]: ...
    def get_by_id(self, doctor_id: int) -> Optional[DoctorEntity]: ...

class IPatientRepository(Protocol):
    def get_by_user_id(self, user_id: int) -> Optional[PatientEntity]: ...
    def create(self, patient: PatientEntity) -> PatientEntity: ...
    def update(self, patient_id: int, patient_data: PatientEntity) -> Optional[PatientEntity]: ...
    def update_doctor(self, patient_id: int, doctor_id: Optional[int]) -> Optional[PatientEntity]: ...
    def get_patients_by_doctor(self, doctor_id: int) -> List[PatientEntity]: ...
    def get_by_id(self, patient_id: int) -> Optional[PatientEntity]: ...

class IReceptionistRepository(Protocol):
    def get_by_user_id(self, user_id: int) -> Optional[ReceptionistEntity]: ...
    def create(self, receptionist: ReceptionistEntity) -> ReceptionistEntity: ...
    def get_by_doctor_id(self, doctor_id: int) -> List[UserEntity]: ...
    def get_by_id(self, receptionist_id: int) -> Optional[ReceptionistEntity]: ...

class IInvitationCodeRepository(Protocol):
    def get_by_code(self, code: str) -> Optional[InvitationCodeEntity]: ...
    def create(self, doctor_id: int) -> InvitationCodeEntity: ...
    def mark_used(self, code_id: int, patient_id: int) -> Optional[InvitationCodeEntity]: ...

class IUnlinkRequestRepository(Protocol):
    def create(self, patient_id: int, doctor_id: int, reason: Optional[str]) -> UnlinkRequestEntity: ...
    def get_by_id(self, request_id: int) -> Optional[UnlinkRequestEntity]: ...
    def get_pending_for_pair(self, patient_id: int, doctor_id: int) -> Optional[UnlinkRequestEntity]: ...
    def list_by_doctor(self, doctor_id: int, status: Optional[str] = None) -> List[UnlinkRequestEntity]: ...
    def list_by_patient(self, patient_id: int, status: Optional[str] = None) -> List[UnlinkRequestEntity]: ...
    def update_status(self, request_id: int, status: str, resolved_at: Optional[object]) -> Optional[UnlinkRequestEntity]: ...

class IMedicalRecordLookup(Protocol):
    def get_medical_record_id(self, patient_id: int, doctor_id: int) -> Optional[int]: ...
    def get_current_gestational_weeks(self, patient_id: int, doctor_id: int) -> Optional[int]: ...

class IPatientClinicalFilterPort(Protocol):
    """Resuelve qué patient_ids cumplen un criterio clínico que vive en
    `service_transaccional` (medical_records/risk_predictions), sin que usuarios
    haga JOIN directo entre sus tablas y las de otro servicio (ADR-07)."""
    def get_patient_ids_by_risk_cluster(self, doctor_id: int, risk_cluster: str) -> List[int]: ...

class IAppointmentLookup(Protocol):
    def get_appointments_by_patient_id(self, patient_id: int) -> List[object]: ...
    def get_appointments_by_doctor_id(self, doctor_id: int) -> List[object]: ...
    def cancel_future_appointments(self, patient_id: int, doctor_id: int) -> None: ...

# Nota: la inicialización/estado de suscripción (antes ISubscriptionInitializer/
# ISubscriptionStatusLookup) ya no vive en usuarios: la fila la crea el servicio
# pagos on-demand y el estado viaja como claim del JWT (ver servicio auth).

class IPatientLinkedNotifier(Protocol):
    """Avisa la vinculación paciente-doctor a quien de verdad dispara las
    notificaciones (transaccional). Best-effort: una falla de red no debe
    tumbar la vinculación en sí."""
    def notify(self, patient_id: int, doctor_id: int) -> None: ...
